from django.db import models

# Create your models here.


class Owner(models.Model):
    full_name = models.CharField(max_length=255)
    address = models.CharField(max_length=255)
    # id = models.CharField(max_length=255) #  replace with an autogenerated id-pk
    county_state_zip = models.CharField(max_length=50)
    phone_no = models.CharField(max_length=10)

    def __str__(self):
        return self.full_name


class OwnerDetail(models.Model):
    node = models.OneToOneField(Owner, on_delete=models.CASCADE)


class Unit(models.Model):
    name = models.CharField(max_length=255)
    legal_description = models.CharField(max_length=255)
    order_no = models.CharField(max_length=255)
    # id = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class UnitOwner(models.Model):
    owner_id = models.ForeignKey(Owner, on_delete=models.CASCADE)
    unit_id = models.ForeignKey(Unit, on_delete=models.CASCADE)

    current_owner = models.BooleanField(max_length=255)
    interest_type = models.CharField(max_length=255)
    comments = models.CharField(max_length=255)
    vesting_docs = models.CharField(max_length=255)
    interest_decimal = models.DecimalField(max_digits=5, decimal_places=2)
    contacted = models.CharField(max_length=255)

    def __str__(self):
        text = "{user} : {unit}".format(user=self.owner_id, unit=self.unit_id)
        return text

