# Generated by Django 3.1.2 on 2021-12-20 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('county_state_zip', models.CharField(max_length=50)),
                ('phone_no', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('legal_description', models.CharField(max_length=255)),
                ('order_no', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UnitOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_owner', models.BooleanField(max_length=255)),
                ('interest_type', models.CharField(max_length=255)),
                ('comments', models.CharField(max_length=255)),
                ('vesting_docs', models.CharField(max_length=255)),
                ('interest_decimal', models.DecimalField(decimal_places=2, max_digits=5)),
                ('contacted', models.CharField(max_length=255)),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landm.owner')),
                ('unit_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landm.unit')),
            ],
        ),
        migrations.CreateModel(
            name='OwnerDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='landm.owner')),
            ],
        ),
    ]
